name: Run Hello Python Script

on:
  push:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository files
        uses: actions/checkout@v6

      - name: Run hello.py
        run: python hello.py
