name: Validate hello.py

on:
  push:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository files
        uses: actions/checkout@v6

      - name: Validate hello.py against sum test cases
        run: |
          for input in testcases/sum/*.input.txt; do
            expected="${input%.input.txt}.expected.txt"
            echo "Test case: $input"
            python validator.py --input "$input" --expected "$expected"
          done
